/**
 * STPv3.h
 * Copyright ?2006 - 2009 Skyetek, Inc. All Rights Reserved.
 *
 * Header file for SkyeTek Protocol version 3
 */
#ifndef SKYETEK_STPV3_H
#define SKYETEK_STPV3_H

#ifdef __cplusplus
extern "C" {
#endif

#include "SkyeTekAPI.h"

/**
 * SkytekProtocol command flags
 */
typedef enum {
  STPV3_LOOP = 0x0001,
  STPV3_INV = 0x0002,
  STPV3_LOCK = 0x0004,
  STPV3_RF = 0x0008,
  STPV3_AFI = 0x0010,
  STPV3_CRC = 0x0020,
  STPV3_TID = 0x0040,
  STPV3_RID = 0x0080,
  STPV3_ENCRYPTION = 0x0100,
  STPV3_HMAC = 0x0200,
  STPV3_SESSION = 0x0400,
  STPV3_DATA = 0x0800,
  STPV3_RFU = 0xF000
} STPV3_FLAG;

  /* Framing */
#define STPV3_STX 0x02
#define STPV3_ACK 0x06
#define STPV3_NACK 0x15
#define STPV3_CR 0x0D
#define STPV3_LF 0x0A

#define STPV3_TIMEOUT 10000

  /* Request Commands */
#define STPV3_CMD_SELECT_TAG		0x0101
#define STPV3_CMD_READ_TAG		0x0102
#define STPV3_CMD_WRITE_TAG		0x0103
#define STPV3_CMD_ACTIVATE_TAG  	0x0104
#define STPV3_CMD_DEACTIVATE_TAG										0x0105
#define STPV3_CMD_SET_TAG_BIT_RATE									0x0106
#define STPV3_CMD_GET_TAG_INFO											0x0107
#define STPV3_CMD_GET_LOCK_STATUS 									0x0108
#define STPV3_CMD_KILL_TAG 													0x0109
#define STPV3_CMD_REVIVE_TAG 												0x010A
#define STPV3_CMD_ERASE_TAG 												0x010B
#define STPV3_CMD_FORMAT_TAG 												0x010C
#define STPV3_CMD_DESELECT_TAG											0x010D
#define STPV3_CMD_READ_TAG_CONFIG										0x0110
#define STPV3_CMD_WRITE_TAG_CONFIG									0x0111

#define STPV3_CMD_AUTHENTICATE_TAG 									0x0201
#define STPV3_CMD_SEND_TAG_PASSWORD 								0x0202
#define STPV3_CMD_INIT_SECURE_MEMORY                0x0203
#define STPV3_CMD_SETUP_SECURE_MEMORY               0x0204

#define STPV3_CMD_GET_APPLICATION_IDS								0x0301
#define STPV3_CMD_SELECT_APPLICATION 								0x0302
#define STPV3_CMD_CREATE_APPLICATION 								0x0303
#define STPV3_CMD_DELETE_APPLICATION 								0x0304

#define STPV3_CMD_GET_FILE_IDS 											0x0401
#define STPV3_CMD_SELECT_FILE 											0x0402
#define STPV3_CMD_CREATE_FILE 											0x0403
#define STPV3_CMD_GET_FILE_SETTINGS 								0x0404
#define STPV3_CMD_CHANGE_FILE_SETTINGS 							0x0405
#define STPV3_CMD_READ_FILE 												0x0406
#define STPV3_CMD_WRITE_FILE 												0x0407
#define STPV3_CMD_DELETE_FILE 											0x0408
#define STPV3_CMD_CLEAR_FILE 												0x0409

#define STPV3_CMD_CREDIT_VALUE_FILE									0x040A
#define STPV3_CMD_DEBIT_VALUE_FILE									0x040B
#define STPV3_CMD_LIMITED_CREDIT_VALUE_FILE					0x040C
#define STPV3_CMD_GET_VALUE       									0x040D
#define STPV3_CMD_COMMIT_TRANSACTION								0x040E
#define STPV3_CMD_ABORT_TRANSACTION									0x040F
#define STPV3_CMD_READ_RECORDS											0x0410
#define STPV3_CMD_WRITE_RECORD											0x0411
#define	STPV3_CMD_CHANGE_KEY_SETTINGS 							0x0412
#define	STPV3_CMD_GET_KEY_SETTINGS    							0x0413
#define	STPV3_CMD_GET_KEY_VERSION										0x0414
#define	STPV3_CMD_CHANGE_KEY          							0x0415

#define STPV3_CMD_ENABLE_EAS 												0x0501
#define STPV3_CMD_DISABLE_EAS 											0x0502
#define STPV3_CMD_SCAN_EAS 													0x0503
#define STPV3_CMD_WRITE_AFI 												0x0504
#define STPV3_CMD_READ_AFI 													0x0505
#define STPV3_CMD_WRITE_DSFID 											0x0506
#define STPV3_CMD_READ_DSFID 												0x0507

#define STPV3_CMD_STORE_KEY 												0x0601
#define STPV3_CMD_LOAD_KEY 													0x0602

#define STPV3_CMD_INTERFACE_SEND										0x0701
#define STPV3_CMD_TRANSPORT_SEND										0x0702

#define STPV3_CMD_INITIATE_PAYMENT                  0x0801
#define STPV3_CMD_COMPUTE_PAYMENT                   0x0802

#define STPV3_CMD_LOAD_DEFAULTS 										0x1101
#define STPV3_CMD_RESET_DEVICE 											0x1102
#define STPV3_CMD_BOOTLOAD 													0x1103
#define STPV3_CMD_READ_SYSTEM_PARAMETER 						0x1201
#define STPV3_CMD_WRITE_SYSTEM_PARAMETER 						0x1202
#define STPV3_CMD_STORE_DEFAULT_SYSTEM_PARAMETER		0x1301
#define STPV3_CMD_RETRIEVE_DEFAULT_SYSTEM_PARAMETER 0x1302
#define STPV3_CMD_AUTHENTICATE_READER 							0x1401
#define STPV3_CMD_ENABLE_DEBUG 											0x1402
#define STPV3_CMD_DISABLE_DEBUG 										0x1403
#define STPV3_CMD_GET_DEBUG_MESSAGES								0x1404
#define STPV3_CMD_ENTER_PAYMENT_SCAN_MODE           0x1405

  /* Responses */
#define STPV3_RESP_SELECT_TAG_PASS									0x0101
#define STPV3_RESP_SELECT_TAG_LOOP_ON								0x01C1
#define STPV3_RESP_SELECT_TAG_FAIL									0x8101
#define STPV3_RESP_SELECT_TAG_LOOP_OFF							0x81C1
#define STPV3_RESP_SELECT_TAG_INVENTORY_DONE				0x810F
#define STPV3_RESP_READ_TAG_DATA_PASS								0x0102
#define STPV3_RESP_READ_TAG_DATA_FAIL								0x8102
#define STPV3_RESP_WRITE_TAG_DATA_PASS							0x0103
#define STPV3_RESP_WRITE_TAG_DATA_FAIL							0x8103
#define STPV3_RESP_ACTIVATE_TAG_TYPE_PASS						0x0104
#define STPV3_RESP_ACTIVATE_TAG_TYPE_FAIL						0x8104
#define STPV3_RESP_DEACTIVATE_TAG_TYPE_PASS					0x0105
#define STPV3_RESP_DEACTIVATE_TAG_TYPE_FAIL					0x8105
#define STPV3_RESP_SET_TAG_BIT_RATE_PASS						0x0106
#define STPV3_RESP_SET_TAG_BIT_RATE_FAIL						0x8106
#define STPV3_RESP_GET_TAG_INFO_PASS								0x0107
#define STPV3_RESP_GET_TAG_INFO_FAIL								0x8107
#define STPV3_RESP_GET_LOCK_STATUS_PASS							0x0108
#define STPV3_RESP_GET_LOCK_STATUS_FAIL							0x8108
#define STPV3_RESP_KILL_TAG_PASS										0x0109
#define STPV3_RESP_KILL_TAG_FAIL										0x8109
#define STPV3_RESP_REVIVE_TAG_PASS									0x010A
#define STPV3_RESP_REVIVE_TAG_FAIL									0x810A
#define STPV3_RESP_ERASE_TAG_PASS										0x010B
#define STPV3_RESP_ERASE_TAG_FAIL										0x810B
#define STPV3_RESP_FORMAT_TAG_PASS									0x010C
#define STPV3_RESP_FORMAT_TAG_FAIL									0x810C
#define STPV3_RESP_DESELECT_TAG_PASS								0x010D
#define STPV3_RESP_DESELECT_TAG_FAIL								0x810D
#define STPV3_RESP_READ_TAG_CONFIG_PASS							0x0110
#define STPV3_RESP_READ_TAG_CONFIG_FAIL							0x8110
#define STPV3_RESP_WRITE_TAG_CONFIG_PASS						0x0111
#define STPV3_RESP_WRITE_TAG_CONFIG_FAIL						0x8111

#define STPV3_RESP_AUTHENTICATE_TAG_PASS						0x0201
#define STPV3_RESP_AUTHENTICATE_TAG_FAIL						0x8201
#define STPV3_RESP_SEND_TAG_PASSWORD_PASS						0x0202
#define STPV3_RESP_SEND_TAG_PASSWORD_FAIL						0x8202
#define STPV3_RESP_INIT_SECURE_MEMORY_PASS          0x0203
#define STPV3_RESP_INIT_SECURE_MEMORY_FAIL          0x8203
#define STPV3_RESP_SETUP_SECURE_MEMORY_PASS         0x0204
#define STPV3_RESP_SETUP_SECURE_MEMORY_FAIL         0x8204

#define STPV3_RESP_GET_APPLICATION_IDS_PASS					0x0301
#define STPV3_RESP_GET_APPLICATION_IDS_FAIL					0x8301
#define STPV3_RESP_SELECT_APPLICATION_PASS					0x0302
#define STPV3_RESP_SELECT_APPLICATION_FAIL					0x8302
#define STPV3_RESP_CREATE_APPLICATION_PASS					0x0303
#define STPV3_RESP_CREATE_APPLICATION_FAIL					0x8303
#define STPV3_RESP_DELETE_APPLICATION_PASS					0x0304
#define STPV3_RESP_DELETE_APPLICATION_FAIL					0x8304

#define STPV3_RESP_GET_FILE_IDS_PASS 								0x0401
#define STPV3_RESP_GET_FILE_IDS_FAIL 								0x8401
#define STPV3_RESP_SELECT_FILE_PASS 								0x0402
#define STPV3_RESP_SELECT_FILE_FAIL									0x8402
#define STPV3_RESP_CREATE_FILE_PASS 								0x0403
#define STPV3_RESP_CREATE_FILE_FAIL 								0x8403
#define STPV3_RESP_GET_FILE_SETTINGS_PASS						0x0404
#define STPV3_RESP_GET_FILE_SETTINGS_FAIL 					0x8404
#define STPV3_RESP_CHANGE_FILE_SETTINGS_PASS				0x0405
#define STPV3_RESP_CHANGE_FILE_SETTINGS_FAIL				0x8405
#define STPV3_RESP_READ_FILE_PASS										0x0406
#define STPV3_RESP_READ_FILE_FAIL 									0x8406
#define STPV3_RESP_WRITE_FILE_PASS 									0x0407
#define STPV3_RESP_WRITE_FILE_FAIL 									0x8407
#define STPV3_RESP_DELETE_FILE_PASS 								0x0408
#define STPV3_RESP_DELETE_FILE_FAIL			 						0x8408
#define STPV3_RESP_CLEAR_FILE_PASS 									0x0409
#define STPV3_RESP_CLEAR_FILE_FAIL 									0x8409

#define STPV3_RESP_CREDIT_VALUE_FILE_PASS 					0x040A
#define STPV3_RESP_CREDIT_VALUE_FILE_FAIL 					0x840A
#define STPV3_RESP_DEBIT_VALUE_FILE_PASS 						0x040B
#define STPV3_RESP_DEBIT_VALUE_FILE_FAIL						0x840B
#define STPV3_RESP_LIMITED_CREDIT_VALUE_FILE_PASS 	0x040C
#define STPV3_RESP_LIMITED_CREDIT_VALUE_FILE_FAIL 	0x840C
#define STPV3_RESP_GET_VALUE_PASS										0x040D
#define STPV3_RESP_GET_VALUE_FAIL 									0x840D
#define STPV3_RESP_COMMIT_TRANSACTION_PASS					0x040E
#define STPV3_RESP_COMMIT_TRANSACTION_FAIL					0x840E
#define STPV3_RESP_ABORT_TRANSACTION_PASS						0x040F
#define STPV3_RESP_ABORT_TRANSACTION_FAIL 					0x840F
#define STPV3_RESP_READ_RECORDS_PASS 								0x0410
#define STPV3_RESP_READ_RECORDS_FAIL 								0x8410
#define STPV3_RESP_WRITE_RECORD_PASS 								0x0411
#define STPV3_RESP_WRITE_RECORD_FAIL			 					0x8411
#define STPV3_RESP_CHANGE_KEY_SETTINGS_PASS 				0x0412
#define STPV3_RESP_CHANGE_KEY_SETTINGS_FAIL 				0x8412
#define STPV3_RESP_GET_KEY_SETTINGS_PASS 						0x0413
#define STPV3_RESP_GET_KEY_SETTINGS_FAIL 						0x8413
#define STPV3_RESP_GET_KEY_VERSION_PASS 						0x0414
#define STPV3_RESP_GET_KEY_VERSION_FAIL 						0x8414
#define STPV3_RESP_CHANGE_KEY_PASS 									0x0415
#define STPV3_RESP_CHANGE_KEY_FAIL 									0x8415

#define STPV3_RESP_ENABLE_EAS_PASS									0x0501
#define STPV3_RESP_ENABLE_EAS_FAIL 									0x8501
#define STPV3_RESP_DISABLE_EAS_PASS 								0x0502
#define STPV3_RESP_DISABLE_EAS_FAIL 								0x8502
#define STPV3_RESP_SCAN_EAS_PASS 										0x0503
#define STPV3_RESP_SCAN_EAS_FAIL 										0x8503
#define STPV3_RESP_WRITE_AFI_PASS 									0x0504
#define STPV3_RESP_WRITE_AFI_FAIL 									0x8504
#define STPV3_RESP_READ_AFI_PASS 										0x0505
#define STPV3_RESP_READ_AFI_FAIL 										0x8505
#define STPV3_RESP_WRITE_DSFID_PASS									0x0506
#define STPV3_RESP_WRITE_DSFID_FAIL 								0x8506
#define STPV3_RESP_READ_DSFID_PASS 									0x0507
#define STPV3_RESP_READ_DSFID_FAIL 									0x8507

#define STPV3_RESP_STORE_KEY_PASS										0x0601
#define STPV3_RESP_STORE_KEY_FAIL 									0x8601
#define STPV3_RESP_LOAD_KEY_PASS 										0x0602
#define STPV3_RESP_LOAD_KEY_FAIL 										0x8602

#define STPV3_RESP_INTERFACE_SEND_PASS		 					0x0701
#define STPV3_RESP_INTERFACE_SEND_FAIL 							0x8701
#define STPV3_RESP_TRANSPORT_SEND_PASS		 					0x0702
#define STPV3_RESP_TRANSPORT_SEND_FAIL 							0x8702

#define STPV3_RESP_INITIATE_PAYMENT_PASS            0x0801
#define STPV3_RESP_INITIATE_PAYMENT_FAIL            0x8801
#define STPV3_RESP_COMPUTE_PAYMENT_PASS             0x0802
#define STPV3_RESP_COMPUTE_PAYMENT_FAIL             0x8802

#define STPV3_RESP_LOAD_DEFAULTS_PASS		 						0x1101
#define STPV3_RESP_LOAD_DEFAULTS_FAIL 							0x9101
#define STPV3_RESP_RESET_DEVICE_PASS 								0x1102
#define STPV3_RESP_RESET_DEVICE_FAIL 								0x9102
#define STPV3_RESP_BOOTLOAD_PASS 										0x1103
#define STPV3_RESP_BOOTLOAD_FAIL										0x9103

#define STPV3_RESP_READ_SYSTEM_PARAMETER_PASS 			0x1201
#define STPV3_RESP_READ_SYSTEM_PARAMETER_FAIL 			0x9201
#define STPV3_RESP_WRITE_SYSTEM_PARAMETER_PASS 			0x1202
#define STPV3_RESP_WRITE_SYSTEM_PARAMETER_FAIL 			0x9202

#define STPV3_RESP_STORE_DEFAULT_SYSTEM_PARAMETER_PASS		0x1301
#define STPV3_RESP_STORE_DEFAULT_SYSTEM_PARAMETER_FAIL		0x9301
#define STPV3_RESP_RETRIEVE_DEFAULT_SYSTEM_PARAMETER_PASS 0x1302
#define STPV3_RESP_RETRIEVE_DEFAULT_SYSTEM_PARAMETER_FAIL 0x9302

#define STPV3_RESP_AUTHENTICATE_READER_PASS					0x1401
#define STPV3_RESP_AUTHENTICATE_READER_FAIL					0x9401
#define STPV3_RESP_ENABLE_DEBUG_PASS								0x1402
#define STPV3_RESP_ENABLE_DEBUG_FAIL								0x9402
#define STPV3_RESP_DISABLE_DEBUG_PASS								0x1403
#define STPV3_RESP_DISABLE_DEBUG_FAIL								0x9403
#define STPV3_RESP_GET_DEBUG_MESSAGES_PASS  				0x1404
#define STPV3_RESP_GET_DEBUG_MESSAGES_FAIL					0x9404
#define STPV3_RESP_ENTER_PAYMENT_SCAN_MODE_PASS			0x1405
#define STPV3_RESP_ENTER_PAYMENT_SCAN_MODE_FAIL 		0x9405

#define STPV3_RESP_INVALID_TAG_TYPE 								0x8001
#define STPV3_RESP_NO_TAG_IN_FIELD									0x8002
#define STPV3_RESP_COLLISION_DETECTED								0x8003
#define STPV3_RESP_TAG_DATA_INTEGRITY_CHECK_FAILED	0x8004
#define STPV3_RESP_TAG_BLOCKS_LOCKED								0x8005
#define STPV3_RESP_NOT_AUTHENTICATED								0x8006
#define STPV3_RESP_NO_TAG_ID_MATCH                  0x8007
#define STPV3_RESP_TAG_DATA_RATE_NOT_SUPPORTED			0x800B
#define STPV3_RESP_ENCRYPT_TAG_DATA_FAIL 						0x800C
#define STPV3_RESP_DECRYPT_TAG_DATA_FAIL 						0x800D
#define STPV3_RESP_INVALID_SIGNATURE_HMAC 					0x800E
#define STPV3_RESP_INVALID_KEY_FOR_AUTHENTICATION		0x800F
#define STPV3_RESP_NO_APPLICATION_PRESENT						0x8010
#define STPV3_RESP_FILE_NOT_FOUND 									0x8011
#define STPV3_RESP_NO_FILE_SELECTED 								0x8012
#define STPV3_RESP_INVALID_KEY_NUMBER 							0x8013
#define STPV3_RESP_INVALID_KEY_LENGTH 							0x8014

#define STPV3_RESP_SCAN_EAS_LOOP_EXIT               0x85C3

#define STPV3_RESP_UNKOWN_ERROR 										0x9001
#define STPV3_RESP_INVALID_COMMAND 									0x9002
#define STPV3_RESP_INVALID_CRC 											0x9003
#define STPV3_RESP_INVALID_MESSAGE_LENGTH						0x9004
#define STPV3_RESP_INVALID_ADDRESS 									0x9005
#define STPV3_RESP_INVALID_FLAGS 										0x9006
#define STPV3_RESP_INVALID_ASCII_CHAR								0x9007
#define STPV3_RESP_INVALID_NUMBER_OF_BLOCKS					0x9008
#define STPV3_RESP_INVALID_DATA_LEN									0x9009
#define STPV3_RESP_INVALID_ENCODING									0x9010
#define STPV3_RESP_INVALID_ARGUMENT									0x9011
#define STPV3_RESP_INVALID_SESSION 									0x9012
#define STPV3_RESP_CMD_NOT_IMPLEMENTED 							0x9013
#define STPV3_RESP_NO_ANTENNA_DETECTED 							0x900F


/*System Parameters*/
#define STPV3_SERIAL			0x00
#define STPV3_FIRMWARE		0x01

/* Lookups for commands and responses */
typedef struct STPV3_CODE_LOOKUP {
	unsigned int cmd;
	TCHAR *name;
} STPV3_CODE_LOOKUP;

static STPV3_CODE_LOOKUP stpv3Commands[] = {
	{STPV3_CMD_SELECT_TAG, _T("SelectTag")},
	{STPV3_CMD_READ_TAG, _T("ReadTag")},
	{STPV3_CMD_WRITE_TAG, _T("WriteTag")},
	{STPV3_CMD_READ_TAG_CONFIG, _T("ReadTagConfig")},
	{STPV3_CMD_WRITE_TAG_CONFIG, _T("WriteTagConfig")},
	{STPV3_CMD_ACTIVATE_TAG, _T("ActivateTag")},
	{STPV3_CMD_DEACTIVATE_TAG, _T("DeactivateTag")},
	{STPV3_CMD_SET_TAG_BIT_RATE, _T("SetTagBitRate")},
	{STPV3_CMD_GET_TAG_INFO, _T("GetTagInfo")},
	{STPV3_CMD_GET_LOCK_STATUS, _T("GetLockStatus")},
	{STPV3_CMD_KILL_TAG, _T("KillTag")},
	{STPV3_CMD_REVIVE_TAG, _T("ReviveTag")},
	{STPV3_CMD_ERASE_TAG, _T("EraseTag")},
	{STPV3_CMD_FORMAT_TAG, _T("FormatTag")},
	{STPV3_CMD_DESELECT_TAG, _T("DeselectTag")},
	{STPV3_CMD_AUTHENTICATE_TAG, _T("AuthenticateTag")},
	{STPV3_CMD_SEND_TAG_PASSWORD, _T("SendTagPassword")},
	{STPV3_CMD_INIT_SECURE_MEMORY, _T("InitializeSecureMemory")},
	{STPV3_CMD_SETUP_SECURE_MEMORY, _T("SetupSecureMemory")},
	{STPV3_CMD_GET_APPLICATION_IDS, _T("GetApplicationIds")},
	{STPV3_CMD_SELECT_APPLICATION, _T("SelectApplication")},
	{STPV3_CMD_CREATE_APPLICATION, _T("CreateApplication")},
	{STPV3_CMD_DELETE_APPLICATION, _T("DeleteApplication")},
	{STPV3_CMD_GET_FILE_IDS, _T("GetFileIds")},
	{STPV3_CMD_SELECT_FILE, _T("SelectFile")},
	{STPV3_CMD_CREATE_FILE, _T("CreateFile")},
	{STPV3_CMD_GET_FILE_SETTINGS, _T("GetFileSettings")},
	{STPV3_CMD_CHANGE_FILE_SETTINGS, _T("ChangeFileSettings")},
	{STPV3_CMD_READ_FILE, _T("ReadFile")},
	{STPV3_CMD_WRITE_FILE, _T("WriteFile")},
	{STPV3_CMD_DELETE_FILE, _T("DeleteFile")},
	{STPV3_CMD_CLEAR_FILE, _T("ClearFile")},
	{STPV3_CMD_CREDIT_VALUE_FILE, _T("CreditValueFile")},
	{STPV3_CMD_DEBIT_VALUE_FILE	, _T("DebitValueFile")},
	{STPV3_CMD_LIMITED_CREDIT_VALUE_FILE, _T("LimitedCreditValueFile")},
	{STPV3_CMD_GET_VALUE, _T("GetValue")},
	{STPV3_CMD_COMMIT_TRANSACTION, _T("CommitTransaction")},
	{STPV3_CMD_ABORT_TRANSACTION, _T("AbortTransaction")},
	{STPV3_CMD_READ_RECORDS, _T("ReadRecords")},
	{STPV3_CMD_WRITE_RECORD, _T("WriteRecord")},
	{STPV3_CMD_ENABLE_EAS, _T("EnableEAS")},
	{STPV3_CMD_DISABLE_EAS, _T("DisableEAS")},
	{STPV3_CMD_SCAN_EAS, _T("ScanEAS")},
	{STPV3_CMD_WRITE_AFI, _T("WriteAFI")},
	{STPV3_CMD_READ_AFI, _T("ReadAFI")},
	{STPV3_CMD_WRITE_DSFID, _T("WriteDSFID")},
	{STPV3_CMD_READ_DSFID, _T("ReadDSFID")},
	{STPV3_CMD_STORE_KEY, _T("StoreKey")},
	{STPV3_CMD_LOAD_KEY, _T("LoadKey")},
	{STPV3_CMD_GET_KEY_VERSION, _T("GetKeyVersion")},
	{STPV3_CMD_CHANGE_KEY, _T("ChangeKey")},
	{STPV3_CMD_CHANGE_KEY_SETTINGS, _T("ChangeKeySettings")},
	{STPV3_CMD_GET_KEY_SETTINGS, _T("GetKeySettings")},
	{STPV3_CMD_INTERFACE_SEND, _T("InterfaceSend")},
	{STPV3_CMD_TRANSPORT_SEND, _T("TransportSend")},
	{STPV3_CMD_LOAD_DEFAULTS, _T("LoadDefaults")},
	{STPV3_CMD_RESET_DEVICE, _T("ResetDevice")},
	{STPV3_CMD_BOOTLOAD, _T("Bootload")},
	{STPV3_CMD_READ_SYSTEM_PARAMETER, _T("ReadSystemParameter")},
	{STPV3_CMD_WRITE_SYSTEM_PARAMETER, _T("WriteSystemParameter")},
	{STPV3_CMD_STORE_DEFAULT_SYSTEM_PARAMETER, _T("StoreDefaultSystemParameter")},
	{STPV3_CMD_RETRIEVE_DEFAULT_SYSTEM_PARAMETER, _T("RetrieveDefaultSystemParameter")},
	{STPV3_CMD_AUTHENTICATE_READER, _T("AuthenticateReader")},
	{STPV3_CMD_ENABLE_DEBUG, _T("EnableDebug")},
	{STPV3_CMD_DISABLE_DEBUG, _T("DisableDebug")},
	{STPV3_CMD_GET_DEBUG_MESSAGES, _T("GetDebugMessages")},
	{STPV3_CMD_INITIATE_PAYMENT, _T("InitiatePayment")},
	{STPV3_CMD_COMPUTE_PAYMENT, _T("ComputePayment")},
	{STPV3_CMD_ENTER_PAYMENT_SCAN_MODE, _T("EnterPaymentScanMode")}
};

static STPV3_CODE_LOOKUP stpv3Responses[] = {
	{STPV3_RESP_SELECT_TAG_LOOP_ON, _T("SelectTag: LOOP ON")},
	{STPV3_RESP_SELECT_TAG_LOOP_OFF, _T("SelectTag: LOOP OFF")},
  {STPV3_RESP_SELECT_TAG_INVENTORY_DONE, _T("SelectTag: INVENTORY DONE")},
	{STPV3_RESP_SELECT_TAG_PASS, _T("SelectTag: PASS")},
	{STPV3_RESP_SELECT_TAG_FAIL, _T("SelectTag: FAIL")},
	{STPV3_RESP_READ_TAG_DATA_PASS, _T("ReadTagData: PASS")},
	{STPV3_RESP_READ_TAG_DATA_FAIL, _T("ReadTagData: FAIL")},
	{STPV3_RESP_WRITE_TAG_DATA_PASS, _T("WriteTagData: PASS")},
	{STPV3_RESP_WRITE_TAG_DATA_FAIL, _T("WriteTagData: FAIL")},
	{STPV3_RESP_READ_TAG_CONFIG_PASS, _T("ReadTagConfig: PASS")},
	{STPV3_RESP_READ_TAG_CONFIG_FAIL, _T("ReadTagConfig: FAIL")},
	{STPV3_RESP_WRITE_TAG_CONFIG_PASS, _T("WriteTagConfig: PASS")},
	{STPV3_RESP_WRITE_TAG_CONFIG_FAIL, _T("WriteTagConfig: FAIL")},
	{STPV3_RESP_ACTIVATE_TAG_TYPE_PASS, _T("ActivateTagType: PASS")},
	{STPV3_RESP_ACTIVATE_TAG_TYPE_FAIL, _T("ActivateTagType: FAIL")},
	{STPV3_RESP_DEACTIVATE_TAG_TYPE_PASS, _T("DeactivateTagType: PASS")},
	{STPV3_RESP_DEACTIVATE_TAG_TYPE_FAIL, _T("DeactivateTagType: FAIL")},
	{STPV3_RESP_SET_TAG_BIT_RATE_PASS, _T("SetTagBitRate: PASS")},
	{STPV3_RESP_SET_TAG_BIT_RATE_FAIL, _T("SetTagBitRate: FAIL")},
	{STPV3_RESP_GET_TAG_INFO_PASS, _T("GetTagInfo: PASS")},
	{STPV3_RESP_GET_TAG_INFO_FAIL, _T("GetTagInfo: FAIL")},
	{STPV3_RESP_GET_LOCK_STATUS_PASS, _T("GetLockStatus: PASS")},
	{STPV3_RESP_GET_LOCK_STATUS_FAIL, _T("GetLockStatus: FAIL")},
	{STPV3_RESP_KILL_TAG_PASS, _T("KillTag: PASS")},
	{STPV3_RESP_KILL_TAG_FAIL, _T("KillTag: FAIL")},
	{STPV3_RESP_REVIVE_TAG_PASS, _T("ReviveTag: PASS")},
	{STPV3_RESP_REVIVE_TAG_FAIL, _T("ReviveTag: FAIL")},
	{STPV3_RESP_ERASE_TAG_PASS, _T("EraseTag: PASS")},
	{STPV3_RESP_ERASE_TAG_FAIL, _T("EraseTag: FAIL")},
	{STPV3_RESP_FORMAT_TAG_PASS, _T("FormatTag: PASS")},
	{STPV3_RESP_FORMAT_TAG_FAIL, _T("FormatTag: FAIL")},
	{STPV3_RESP_DESELECT_TAG_PASS, _T("DeselectTag: PASS")},
	{STPV3_RESP_DESELECT_TAG_FAIL, _T("DeselectTag: FAIL")},

	{STPV3_RESP_AUTHENTICATE_TAG_PASS, _T("AuthenticateTag: PASS")},
	{STPV3_RESP_AUTHENTICATE_TAG_FAIL, _T("AuthenticateTag: FAIL")},
	{STPV3_RESP_SEND_TAG_PASSWORD_PASS, _T("SendTagPassword: PASS")},
	{STPV3_RESP_SEND_TAG_PASSWORD_FAIL, _T("SendTagPassword: FAIL")},

	{STPV3_RESP_GET_APPLICATION_IDS_PASS, _T("GetApplicationIds: PASS")},
	{STPV3_RESP_GET_APPLICATION_IDS_FAIL, _T("GetApplicationIds: FAIL")},
	{STPV3_RESP_SELECT_APPLICATION_PASS, _T("SelectApplication: PASS")},
	{STPV3_RESP_SELECT_APPLICATION_FAIL, _T("SelectApplication: FAIL")},
	{STPV3_RESP_CREATE_APPLICATION_PASS, _T("CreateApplication: PASS")},
	{STPV3_RESP_CREATE_APPLICATION_FAIL, _T("CreateApplication: FAIL")},
	{STPV3_RESP_DELETE_APPLICATION_PASS, _T("DeleteApplication: PASS")},
	{STPV3_RESP_DELETE_APPLICATION_FAIL, _T("DeleteApplication: FAIL")},

	{STPV3_RESP_GET_FILE_IDS_PASS, _T("GetFileIds: PASS")},
	{STPV3_RESP_GET_FILE_IDS_FAIL, _T("GetFileIds: FAIL")},
	{STPV3_RESP_SELECT_FILE_PASS, _T("SelectFile: PASS")},
	{STPV3_RESP_SELECT_FILE_FAIL, _T("SelectFile: FAIL")},
	{STPV3_RESP_CREATE_FILE_PASS, _T("CreateFile: PASS")},
	{STPV3_RESP_CREATE_FILE_FAIL, _T("CreateFile: FAIL")},
	{STPV3_RESP_GET_FILE_SETTINGS_PASS, _T("GetFileSettings: PASS")},
	{STPV3_RESP_GET_FILE_SETTINGS_FAIL, _T("GetFileSettings: FAIL")},
	{STPV3_RESP_CHANGE_FILE_SETTINGS_PASS, _T("ChangeFileSettings: PASS")},
	{STPV3_RESP_CHANGE_FILE_SETTINGS_FAIL, _T("ChangeFileSettings: FAIL")},
	{STPV3_RESP_READ_FILE_PASS, _T("ReadFile: PASS")},
	{STPV3_RESP_READ_FILE_FAIL, _T("ReadFile: FAIL")},
	{STPV3_RESP_WRITE_FILE_PASS, _T("WriteFile: PASS")},
	{STPV3_RESP_WRITE_FILE_FAIL, _T("WriteFile: FAIL")},
	{STPV3_RESP_DELETE_FILE_PASS, _T("DeleteFile: PASS")},
	{STPV3_RESP_DELETE_FILE_FAIL, _T("DeleteFile: FAIL")},
	{STPV3_RESP_CLEAR_FILE_PASS, _T("ClearFile: PASS")},
	{STPV3_RESP_CLEAR_FILE_FAIL, _T("ClearFile: FAIL")},

  {STPV3_RESP_CREDIT_VALUE_FILE_PASS, _T("CreditValueFile: PASS")},
  {STPV3_RESP_CREDIT_VALUE_FILE_FAIL, _T("CreditValueFile: FAIL")},
  {STPV3_RESP_DEBIT_VALUE_FILE_PASS, _T("DebitValueFile: PASS")},
  {STPV3_RESP_DEBIT_VALUE_FILE_FAIL, _T("DebitValueFile: FAIL")},
  {STPV3_RESP_LIMITED_CREDIT_VALUE_FILE_PASS, _T("LimitedCreditValueFile: PASS")},
  {STPV3_RESP_LIMITED_CREDIT_VALUE_FILE_FAIL, _T("LimitedCreditValueFile: FAIL")},
  {STPV3_RESP_GET_VALUE_PASS, _T("GetValue: PASS")},
  {STPV3_RESP_GET_VALUE_FAIL, _T("GetValue: FAIL")},
  {STPV3_RESP_COMMIT_TRANSACTION_PASS, _T("CommitTransaction: PASS")},
  {STPV3_RESP_COMMIT_TRANSACTION_FAIL, _T("CommitTransaction: FAIL")},
  {STPV3_RESP_ABORT_TRANSACTION_PASS, _T("AbortTransaction: PASS")},
  {STPV3_RESP_ABORT_TRANSACTION_FAIL, _T("AbortTransaction: FAIL")},
  {STPV3_RESP_READ_RECORDS_PASS, _T("ReadRecords: PASS")},
  {STPV3_RESP_READ_RECORDS_FAIL, _T("ReadRecords: FAIL")},
  {STPV3_RESP_WRITE_RECORD_PASS, _T("WriteRecord: PASS")},
  {STPV3_RESP_WRITE_RECORD_FAIL, _T("WriteRecord: FAIL")},

	{STPV3_RESP_ENABLE_EAS_PASS, _T("EnableEAS: PASS")},
	{STPV3_RESP_ENABLE_EAS_FAIL, _T("EnableEAS: FAIL")},
	{STPV3_RESP_DISABLE_EAS_PASS, _T("DisableEAS: PASS")},
	{STPV3_RESP_DISABLE_EAS_FAIL, _T("DisableEAS: FAIL")},
	{STPV3_RESP_SCAN_EAS_PASS, _T("ScanEAS: PASS")},
	{STPV3_RESP_SCAN_EAS_FAIL, _T("ScanEAS: FAIL")},
	{STPV3_RESP_WRITE_AFI_PASS, _T("WriteAFI: PASS")},
	{STPV3_RESP_WRITE_AFI_FAIL, _T("WriteAFI: FAIL")},
	{STPV3_RESP_READ_AFI_PASS, _T("ReadAFI: PASS")},
	{STPV3_RESP_READ_AFI_FAIL, _T("ReadAFI: FAIL")},
	{STPV3_RESP_WRITE_DSFID_PASS, _T("WriteDSFID: PASS")},
	{STPV3_RESP_WRITE_DSFID_FAIL, _T("WriteDSFID: FAIL")},
	{STPV3_RESP_READ_DSFID_PASS, _T("ReadDSFID: PASS")},
	{STPV3_RESP_READ_DSFID_FAIL, _T("ReadDSFID: FAIL")},

	{STPV3_RESP_STORE_KEY_PASS, _T("StoreKey: PASS")},
	{STPV3_RESP_STORE_KEY_FAIL, _T("StoreKey: FAIL")},
	{STPV3_RESP_LOAD_KEY_PASS, _T("LoadKey: PASS")},
	{STPV3_RESP_LOAD_KEY_FAIL, _T("LoadKey: FAIL")},
	{STPV3_RESP_GET_KEY_VERSION_PASS, _T("GetKeyVersion: PASS")},
	{STPV3_RESP_GET_KEY_VERSION_FAIL, _T("GetKeyVersion: FAIL")},
	{STPV3_RESP_CHANGE_KEY_PASS, _T("ChangeKey: PASS")},
	{STPV3_RESP_CHANGE_KEY_FAIL, _T("ChangeKey: FAIL")},
	{STPV3_RESP_CHANGE_KEY_SETTINGS_PASS, _T("ChangeKeySettings: PASS")},
	{STPV3_RESP_CHANGE_KEY_SETTINGS_FAIL, _T("ChangeKeySettings: FAIL")},
	{STPV3_RESP_GET_KEY_SETTINGS_PASS, _T("GetKeySettings: PASS")},
	{STPV3_RESP_GET_KEY_SETTINGS_FAIL, _T("GetKeySettings: FAIL")},
	{STPV3_RESP_INIT_SECURE_MEMORY_PASS, _T("InitializeSecureMemory: PASS")},
  {STPV3_RESP_INIT_SECURE_MEMORY_FAIL, _T("InitializeSecureMemory: FAIL")},
	{STPV3_RESP_SETUP_SECURE_MEMORY_PASS, _T("SetupSecureMemory: PASS")},
  {STPV3_RESP_SETUP_SECURE_MEMORY_FAIL, _T("SetupSecureMemory: FAIL")},

	{STPV3_RESP_INTERFACE_SEND_PASS, _T("InterfaceSend: PASS")},
	{STPV3_RESP_INTERFACE_SEND_FAIL, _T("InterfaceSend: FAIL")},
	{STPV3_RESP_TRANSPORT_SEND_PASS, _T("TransportSend: PASS")},
	{STPV3_RESP_TRANSPORT_SEND_FAIL, _T("TransportSend: FAIL")},

	{STPV3_RESP_LOAD_DEFAULTS_PASS, _T("LoadDefaults: PASS")},
	{STPV3_RESP_LOAD_DEFAULTS_FAIL, _T("LoadDefaults: FAIL")},
	{STPV3_RESP_RESET_DEVICE_PASS, _T("ResetDevice: PASS")},
	{STPV3_RESP_RESET_DEVICE_FAIL, _T("ResetDevice: FAIL")},
	{STPV3_RESP_BOOTLOAD_PASS, _T("Bootload: PASS")},
	{STPV3_RESP_BOOTLOAD_FAIL, _T("Bootload: FAIL")},

	{STPV3_RESP_READ_SYSTEM_PARAMETER_PASS, _T("ReadSystemParameter: PASS")},
	{STPV3_RESP_READ_SYSTEM_PARAMETER_FAIL, _T("ReadSystemParameter: FAIL")},
	{STPV3_RESP_WRITE_SYSTEM_PARAMETER_PASS, _T("WriteSystemParameter: PASS")},
	{STPV3_RESP_WRITE_SYSTEM_PARAMETER_FAIL, _T("WriteSystemParameter: FAIL")},
	{STPV3_RESP_STORE_DEFAULT_SYSTEM_PARAMETER_PASS, _T("StoreDefaultSystemParameter: PASS")},
	{STPV3_RESP_STORE_DEFAULT_SYSTEM_PARAMETER_FAIL, _T("StoreDefaultSystemParameter: FAIL")},
	{STPV3_RESP_RETRIEVE_DEFAULT_SYSTEM_PARAMETER_PASS, _T("RetrieveDefaultSystemParameter: PASS")},
	{STPV3_RESP_RETRIEVE_DEFAULT_SYSTEM_PARAMETER_FAIL, _T("RetrieveDefaultSystemParameter: FAIL")},

	{STPV3_RESP_AUTHENTICATE_READER_PASS, _T("AuthenticateReader: PASS")},
	{STPV3_RESP_AUTHENTICATE_READER_FAIL, _T("AuthenticateReader: FAIL")},
	{STPV3_RESP_ENABLE_DEBUG_PASS, _T("EnableDebug: PASS")},
	{STPV3_RESP_ENABLE_DEBUG_FAIL, _T("EnableDebug: FAIL")},
	{STPV3_RESP_DISABLE_DEBUG_PASS, _T("DisableDebug: PASS")},
	{STPV3_RESP_DISABLE_DEBUG_FAIL, _T("DisableDebug: FAIL")},
	{STPV3_RESP_GET_DEBUG_MESSAGES_PASS, _T("GetDebugMessages: PASS")},
	{STPV3_RESP_GET_DEBUG_MESSAGES_FAIL, _T("GetDebugMessages: FAIL")},

	{STPV3_RESP_INITIATE_PAYMENT_PASS, _T("InitiatePayment: PASS")},
	{STPV3_RESP_INITIATE_PAYMENT_FAIL, _T("InitiatePayment: FAIL")},
	{STPV3_RESP_COMPUTE_PAYMENT_PASS, _T("ComputePayment: PASS")},
	{STPV3_RESP_COMPUTE_PAYMENT_FAIL, _T("ComputePayment: FAIL")},
	{STPV3_RESP_ENTER_PAYMENT_SCAN_MODE_PASS, _T("EnterPaymentScanMode: PASS")},
	{STPV3_RESP_ENTER_PAYMENT_SCAN_MODE_FAIL, _T("EnterPaymentScanMode: FAIL")},

	{STPV3_RESP_INVALID_TAG_TYPE, _T("INVALID TAG TYPE")},
	{STPV3_RESP_NO_TAG_IN_FIELD, _T("NO TAG IN FIELD")},
  	{STPV3_RESP_NO_TAG_ID_MATCH, _T("NO TAG ID MATCH")},
	{STPV3_RESP_COLLISION_DETECTED, _T("COLLISION DETECTED")},
	{STPV3_RESP_TAG_DATA_INTEGRITY_CHECK_FAILED, _T("TAG DATA INTEGRRITY CHECK FAILED")},
	{STPV3_RESP_TAG_BLOCKS_LOCKED, _T("TAG BLOCKS LOCKED")},
	{STPV3_RESP_NOT_AUTHENTICATED, _T("NOT AUTHENTICATED")},
	{STPV3_RESP_TAG_DATA_RATE_NOT_SUPPORTED, _T("TAG DATA RATE NOT SUPPORTED")},
	{STPV3_RESP_ENCRYPT_TAG_DATA_FAIL, _T("ENCRYPT TAG DATA FAILED")},
	{STPV3_RESP_DECRYPT_TAG_DATA_FAIL, _T("DECRYPT TAG DATA FAILED")},
	{STPV3_RESP_INVALID_SIGNATURE_HMAC, _T("INVALID SIGNATURE HMAC")},
	{STPV3_RESP_INVALID_KEY_FOR_AUTHENTICATION, _T("INVALID KEY FOR AUTHENTICATION")},
	{STPV3_RESP_NO_APPLICATION_PRESENT, _T("NO APPLICATION PRESENT")},
	{STPV3_RESP_FILE_NOT_FOUND, _T("FILE NOT FOUND")},
	{STPV3_RESP_NO_FILE_SELECTED, _T("NO FILE SELECTED")},
	{STPV3_RESP_INVALID_KEY_NUMBER, _T("INVALID KEY NUMBER")},
	{STPV3_RESP_INVALID_KEY_LENGTH, _T("INVALID KEY LENGTH")},

	{STPV3_RESP_SCAN_EAS_LOOP_EXIT, _T("ScanEAS: LOOP OFF")},

	{STPV3_RESP_UNKOWN_ERROR, _T("UNKNOWN ERROR")},
	{STPV3_RESP_INVALID_COMMAND, _T("INVALID COMMAND")},
	{STPV3_RESP_INVALID_CRC, _T("INVALID CRC")},
	{STPV3_RESP_INVALID_MESSAGE_LENGTH, _T("INVALID MESSAGE LENGTH")},
	{STPV3_RESP_INVALID_ADDRESS, _T("INVALID ADDRESS")},
	{STPV3_RESP_INVALID_FLAGS, _T("INVALID FLAGS")},
	{STPV3_RESP_INVALID_ASCII_CHAR, _T("INVALID ASCII CHARACTER")},
	{STPV3_RESP_INVALID_NUMBER_OF_BLOCKS, _T("INVALID NUMBER OF BLOCKS")},
	{STPV3_RESP_INVALID_DATA_LEN, _T("INVALID DATA LENGTH")},
	{STPV3_RESP_INVALID_ENCODING, _T("INVALID ENCODING")},
	{STPV3_RESP_INVALID_ARGUMENT, _T("INVALID ARGUMENT")},
	{STPV3_RESP_INVALID_SESSION, _T("INVALID SESSION")},
  	{STPV3_RESP_CMD_NOT_IMPLEMENTED, _T("COMMAND NOT IMPLEMENTED")},
	{STPV3_RESP_NO_ANTENNA_DETECTED, _T("NO ANTENNA DETECTED")}
};

#define STPV3_CMD_LOOKUPS_COUNT sizeof(stpv3Commands)/sizeof(STPV3_CODE_LOOKUP) 
#define STPV3_RESP_LOOKUPS_COUNT sizeof(stpv3Responses)/sizeof(STPV3_CODE_LOOKUP) 

typedef struct STPV3_STATUS_LOOKUP {
	unsigned int cmd;
	SKYETEK_STATUS status;
} STPV3_STATUS_LOOKUP;

static STPV3_STATUS_LOOKUP stpv3Statuses[] = {
	{STPV3_RESP_SELECT_TAG_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_SELECT_TAG_FAIL, SKYETEK_FAILURE},
  {STPV3_RESP_SELECT_TAG_INVENTORY_DONE, SKYETEK_SUCCESS},
	{STPV3_RESP_READ_TAG_DATA_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_READ_TAG_DATA_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_WRITE_TAG_DATA_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_WRITE_TAG_DATA_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_READ_TAG_CONFIG_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_READ_TAG_CONFIG_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_WRITE_TAG_CONFIG_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_WRITE_TAG_CONFIG_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_ACTIVATE_TAG_TYPE_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_ACTIVATE_TAG_TYPE_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_DEACTIVATE_TAG_TYPE_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_DEACTIVATE_TAG_TYPE_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_SET_TAG_BIT_RATE_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_SET_TAG_BIT_RATE_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_GET_TAG_INFO_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_GET_TAG_INFO_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_GET_LOCK_STATUS_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_GET_LOCK_STATUS_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_KILL_TAG_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_KILL_TAG_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_REVIVE_TAG_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_REVIVE_TAG_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_ERASE_TAG_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_ERASE_TAG_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_FORMAT_TAG_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_FORMAT_TAG_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_DESELECT_TAG_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_DESELECT_TAG_FAIL, SKYETEK_FAILURE},

	{STPV3_RESP_AUTHENTICATE_TAG_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_AUTHENTICATE_TAG_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_SEND_TAG_PASSWORD_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_SEND_TAG_PASSWORD_FAIL, SKYETEK_FAILURE},

	{STPV3_RESP_GET_APPLICATION_IDS_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_GET_APPLICATION_IDS_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_SELECT_APPLICATION_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_SELECT_APPLICATION_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_CREATE_APPLICATION_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_CREATE_APPLICATION_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_DELETE_APPLICATION_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_DELETE_APPLICATION_FAIL, SKYETEK_FAILURE},

	{STPV3_RESP_GET_FILE_IDS_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_GET_FILE_IDS_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_SELECT_FILE_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_SELECT_FILE_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_CREATE_FILE_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_CREATE_FILE_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_GET_FILE_SETTINGS_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_GET_FILE_SETTINGS_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_CHANGE_FILE_SETTINGS_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_CHANGE_FILE_SETTINGS_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_READ_FILE_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_READ_FILE_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_WRITE_FILE_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_WRITE_FILE_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_DELETE_FILE_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_DELETE_FILE_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_CLEAR_FILE_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_CLEAR_FILE_FAIL, SKYETEK_FAILURE},

  {STPV3_RESP_CREDIT_VALUE_FILE_PASS, SKYETEK_SUCCESS},
  {STPV3_RESP_CREDIT_VALUE_FILE_FAIL, SKYETEK_FAILURE},
  {STPV3_RESP_DEBIT_VALUE_FILE_PASS, SKYETEK_SUCCESS},
  {STPV3_RESP_DEBIT_VALUE_FILE_FAIL, SKYETEK_FAILURE},
  {STPV3_RESP_LIMITED_CREDIT_VALUE_FILE_PASS, SKYETEK_SUCCESS},
  {STPV3_RESP_LIMITED_CREDIT_VALUE_FILE_FAIL, SKYETEK_FAILURE},
  {STPV3_RESP_GET_VALUE_PASS, SKYETEK_SUCCESS},
  {STPV3_RESP_GET_VALUE_FAIL, SKYETEK_FAILURE},
  {STPV3_RESP_COMMIT_TRANSACTION_PASS, SKYETEK_SUCCESS},
  {STPV3_RESP_COMMIT_TRANSACTION_FAIL, SKYETEK_FAILURE},
  {STPV3_RESP_ABORT_TRANSACTION_PASS, SKYETEK_SUCCESS},
  {STPV3_RESP_ABORT_TRANSACTION_FAIL, SKYETEK_FAILURE},
  {STPV3_RESP_READ_RECORDS_PASS, SKYETEK_SUCCESS},
  {STPV3_RESP_READ_RECORDS_FAIL, SKYETEK_FAILURE},
  {STPV3_RESP_WRITE_RECORD_PASS, SKYETEK_SUCCESS},
  {STPV3_RESP_WRITE_RECORD_FAIL, SKYETEK_FAILURE},

	{STPV3_RESP_ENABLE_EAS_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_ENABLE_EAS_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_DISABLE_EAS_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_DISABLE_EAS_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_SCAN_EAS_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_SCAN_EAS_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_WRITE_AFI_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_WRITE_AFI_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_READ_AFI_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_READ_AFI_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_WRITE_DSFID_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_WRITE_DSFID_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_READ_DSFID_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_READ_DSFID_FAIL, SKYETEK_FAILURE},

	{STPV3_RESP_STORE_KEY_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_STORE_KEY_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_LOAD_KEY_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_LOAD_KEY_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_GET_KEY_VERSION_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_GET_KEY_VERSION_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_CHANGE_KEY_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_CHANGE_KEY_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_CHANGE_KEY_SETTINGS_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_CHANGE_KEY_SETTINGS_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_GET_KEY_SETTINGS_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_GET_KEY_SETTINGS_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_INIT_SECURE_MEMORY_PASS, SKYETEK_SUCCESS},
  {STPV3_RESP_INIT_SECURE_MEMORY_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_SETUP_SECURE_MEMORY_PASS, SKYETEK_SUCCESS},
  {STPV3_RESP_SETUP_SECURE_MEMORY_FAIL, SKYETEK_FAILURE},

	{STPV3_RESP_INTERFACE_SEND_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_INTERFACE_SEND_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_TRANSPORT_SEND_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_TRANSPORT_SEND_FAIL, SKYETEK_FAILURE},

	{STPV3_RESP_LOAD_DEFAULTS_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_LOAD_DEFAULTS_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_RESET_DEVICE_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_RESET_DEVICE_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_BOOTLOAD_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_BOOTLOAD_FAIL, SKYETEK_FAILURE},

	{STPV3_RESP_READ_SYSTEM_PARAMETER_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_READ_SYSTEM_PARAMETER_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_WRITE_SYSTEM_PARAMETER_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_WRITE_SYSTEM_PARAMETER_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_STORE_DEFAULT_SYSTEM_PARAMETER_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_STORE_DEFAULT_SYSTEM_PARAMETER_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_RETRIEVE_DEFAULT_SYSTEM_PARAMETER_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_RETRIEVE_DEFAULT_SYSTEM_PARAMETER_FAIL, SKYETEK_FAILURE},

	{STPV3_RESP_AUTHENTICATE_READER_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_AUTHENTICATE_READER_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_ENABLE_DEBUG_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_ENABLE_DEBUG_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_DISABLE_DEBUG_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_DISABLE_DEBUG_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_GET_DEBUG_MESSAGES_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_GET_DEBUG_MESSAGES_FAIL, SKYETEK_FAILURE},
	{STPV3_RESP_ENTER_PAYMENT_SCAN_MODE_PASS, SKYETEK_SUCCESS},
	{STPV3_RESP_ENTER_PAYMENT_SCAN_MODE_FAIL, SKYETEK_FAILURE},

	{STPV3_RESP_INVALID_TAG_TYPE, SKYETEK_INVALID_TAG_TYPE},
	{STPV3_RESP_NO_TAG_IN_FIELD, SKYETEK_TAG_NOT_IN_FIELD},
  {STPV3_RESP_NO_TAG_ID_MATCH, SKYETEK_NO_TAG_ID_MATCH},
	{STPV3_RESP_COLLISION_DETECTED, SKYETEK_COLLISION_DETECTED},
	{STPV3_RESP_TAG_DATA_INTEGRITY_CHECK_FAILED, SKYETEK_TAG_DATA_INTEGRITY_CHECK_FAILED},
	{STPV3_RESP_TAG_BLOCKS_LOCKED, SKYETEK_TAG_BLOCKS_LOCKED},
	{STPV3_RESP_NOT_AUTHENTICATED, SKYETEK_NOT_AUTHENTICATED},
	{STPV3_RESP_TAG_DATA_RATE_NOT_SUPPORTED, SKYETEK_TAG_DATA_RATE_NOT_SUPPORTED},
	{STPV3_RESP_ENCRYPT_TAG_DATA_FAIL, SKYETEK_ENCRYPT_TAG_DATA_FAIL},
	{STPV3_RESP_DECRYPT_TAG_DATA_FAIL, SKYETEK_DECRYPT_TAG_DATA_FAIL},
	{STPV3_RESP_INVALID_SIGNATURE_HMAC, SKYETEK_INVALID_SIGNATURE_HMAC},
	{STPV3_RESP_INVALID_KEY_FOR_AUTHENTICATION, SKYETEK_INVALID_KEY_FOR_AUTHENTICATION},
	{STPV3_RESP_NO_APPLICATION_PRESENT, SKYETEK_NO_APPLICATION_PRESENT},
	{STPV3_RESP_FILE_NOT_FOUND, SKYETEK_FILE_NOT_FOUND},
	{STPV3_RESP_NO_FILE_SELECTED, SKYETEK_NO_FILE_SELECTED},
	{STPV3_RESP_INVALID_KEY_NUMBER, SKYETEK_INVALID_KEY_NUMBER},
	{STPV3_RESP_INVALID_KEY_LENGTH, SKYETEK_INVALID_KEY_LENGTH},

	{STPV3_RESP_UNKOWN_ERROR, SKYETEK_UNKOWN_ERROR},
	{STPV3_RESP_INVALID_COMMAND, SKYETEK_INVALID_COMMAND},
	{STPV3_RESP_INVALID_CRC, SKYETEK_INVALID_CRC},
	{STPV3_RESP_INVALID_MESSAGE_LENGTH, SKYETEK_INVALID_MESSAGE_LENGTH},
	{STPV3_RESP_INVALID_ADDRESS, SKYETEK_INVALID_ADDRESS},
	{STPV3_RESP_INVALID_FLAGS, SKYETEK_INVALID_FLAGS},
	{STPV3_RESP_INVALID_ASCII_CHAR, SKYETEK_INVALID_ASCII_CHAR},
	{STPV3_RESP_INVALID_NUMBER_OF_BLOCKS, SKYETEK_INVALID_NUMBER_OF_BLOCKS},
	{STPV3_RESP_INVALID_DATA_LEN, SKYETEK_INVALID_DATA_LEN},
	{STPV3_RESP_INVALID_ENCODING, SKYETEK_INVALID_ENCODING},
	{STPV3_RESP_INVALID_ARGUMENT, SKYETEK_INVALID_ARGUMENT},
	{STPV3_RESP_INVALID_SESSION, SKYETEK_INVALID_SESSION},
  {STPV3_RESP_CMD_NOT_IMPLEMENTED, SKYETEK_NOT_SUPPORTED},
	{STPV3_RESP_NO_ANTENNA_DETECTED, SKYETEK_NO_ANTENNA_DETECTED}
};

#define STPV3_STATUS_LOOKUPS_COUNT sizeof(stpv3Statuses)/sizeof(STPV3_STATUS_LOOKUP) 

/**
 * Bootloader defintions and types.
 */
#define QUERY_BOOTLDR_VER			    0x01
#define GET_SYSTEM_DEFAULTS			  0x02
#define PROGRAM_DEFAULTS			    0x03
#define WRITE_DATA					      0x04
#define SELECT_ENCRYPTION_SCHEME	0x05
#define RESET_RESTART_DEVICE  		0x06
#define UPDATE_COMPLETE_RESET		  0x07
#define SETUP_BOOTLOADER			    0x08


/**
 * Function defintions.
 */
SKYETEK_STATUS 
STPV3_SendCommand(
    LPSKYETEK_READER     lpReader,
    unsigned int         cmd,
    unsigned int         extraFlags,
    unsigned int          retries
    );

SKYETEK_STATUS 
STPV3_SendSetCommand(
    LPSKYETEK_READER     lpReader,
    unsigned int         cmd,
    unsigned int         extraFlags,
    LPSKYETEK_DATA       lpData,
    unsigned int          retries
    );

SKYETEK_STATUS 
STPV3_SendAddrGetCommand(
    LPSKYETEK_READER     lpReader,
    LPSKYETEK_ADDRESS    lpAddr,
    unsigned int         cmd,
    unsigned int         extraFlags,
    LPSKYETEK_DATA       *lpData,
    unsigned int          retries
    );

SKYETEK_STATUS 
STPV3_SendAddrSetCommand(
    LPSKYETEK_READER     lpReader,
    LPSKYETEK_ADDRESS    lpAddr,
    unsigned int         cmd,
    unsigned int         extraFlags,
    LPSKYETEK_DATA       lpData,
    unsigned int          retries
    );

SKYETEK_STATUS 
STPV3_SendTagCommand(
    LPSKYETEK_READER     lpReader,
    LPSKYETEK_TAG        lpTag,
    unsigned int         cmd,
    unsigned int         extraFlags,
    unsigned int          retries
    );

SKYETEK_STATUS 
STPV3_SendGetTagCommand(
    LPSKYETEK_READER     lpReader,
    LPSKYETEK_TAG        lpTag,
    unsigned int         cmd,
    unsigned int         extraFlags,
    LPSKYETEK_DATA       *lpData,
    unsigned int          retries
    );

SKYETEK_STATUS 
STPV3_SendSetTagCommand(
    LPSKYETEK_READER     lpReader,
    LPSKYETEK_TAG        lpTag,
    unsigned int         cmd,
    unsigned int         extraFlags,
    LPSKYETEK_DATA       lpData,
    unsigned int          retries
    );

SKYETEK_STATUS 
STPV3_SendGetSetTagCommand(
    LPSKYETEK_READER     lpReader,
    LPSKYETEK_TAG        lpTag,
    unsigned int         cmd,
    unsigned int         extraFlags,
    LPSKYETEK_DATA       lpSendData,
    LPSKYETEK_DATA       *lpRecvData,
    unsigned int          retries
    );

SKYETEK_STATUS 
STPV3_SendAddrGetTagCommand(
    LPSKYETEK_READER     lpReader,
    LPSKYETEK_TAG        lpTag,
    LPSKYETEK_ADDRESS    lpAddr,
    unsigned int         cmd,
    unsigned int         extraFlags,
    LPSKYETEK_DATA       *lpData,
    unsigned int          retries
    );

SKYETEK_STATUS 
STPV3_SendAddrSetTagCommand(
    LPSKYETEK_READER     lpReader,
    LPSKYETEK_TAG        lpTag,
    LPSKYETEK_ADDRESS    lpAddr,
    unsigned int         cmd,
    unsigned int         extraFlags,
    LPSKYETEK_DATA       lpData,
    unsigned int          retries
    );

SKYETEK_STATUS 
STPV3_SendAddrGetSetTagCommand(
    LPSKYETEK_READER     lpReader,
    LPSKYETEK_TAG        lpTag,
    LPSKYETEK_ADDRESS    lpAddr,
    unsigned int         cmd,
    unsigned int         extraFlags,
    LPSKYETEK_DATA       lpSendData,
    LPSKYETEK_DATA       *lpRecvData,
    unsigned int          retries
    );

SKYETEK_STATUS 
STPV3_GetStatus(
  unsigned int code
  );

unsigned char 
STPV3_IsErrorResponse(
  unsigned int code
  );


#ifdef __cplusplus
}
#endif

#endif 
