@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM
@REM Read about available command line parameters in the C-SPY Debugging
@REM Guide. Hints about additional command line parameters that may be
@REM useful in specific cases:
@REM   --download_only   Downloads a code image without starting a debug
@REM                     session afterwards.
@REM   --silent          Omits the sign-on message.
@REM   --timeout         Limits the maximum allowed execution time.
@REM 


"C:\Disk_2\IAR_6.60\common\bin\cspybat" "C:\Disk_2\IAR_6.60\arm\bin\armproc.dll" "C:\Disk_2\IAR_6.60\arm\bin\armjlink.dll"  %1 --plugin "C:\Disk_2\IAR_6.60\arm\bin\armbat.dll" --macro "C:\Disk_2\IAR_6.60\arm\config\debugger\ST\Trace_STM32W1xx.dmac" --flash_loader "C:\Disk_2\IAR_6.60\arm\config\flashloader\ST\FlashSTM32W108xC.board" --backend -B "--endian=little" "--cpu=Cortex-M3" "--fpu=None" "-p" "Z:\mz_data\SNT_MOTES\STM32W108XX_SIMPLEMAC_V2.0.1\Projects\SIMPLEMAC\Talk\EWARM\STM32W108.svd" "--drv_verify_download" "--semihosting" "--device=STM32W108CC" "--drv_communication=USB0" "--jlink_speed=auto" "--jlink_initial_speed=32" "--jlink_reset_strategy=0,0" "--jlink_interface=SWD" "--drv_catch_exceptions=0x000" "--drv_swo_clock_setup=72000000,0,2000000" 


